# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class GoogleBookScraper < Formula
  desc "Tool for downloading the contents of books hosted on books.google.com for offlin"
  homepage "https://github.com/shloop/google-book-scraper"
  url "https://github.com/shloop/google-book-scraper/archive/refs/tags/v0.4.0.tar.gz"
  sha256 "00ae8b854b87b270eee64cf6e5d6e9bbf56c5bee1b93d10247f7626c58d0d2eb"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/shloop/google-book-scraper/releases/download/v0.4.0/google-book-scraper-0.4.0-darwin-amd64.tar.gz"
      sha256 "d8c0983efda6e01254f1ea52af6ec2993c013a4e88f8708db317a4215de7e90b"
    end

    on_arm do
      url "https://github.com/shloop/google-book-scraper/releases/download/v0.4.0/google-book-scraper-0.4.0-darwin-arm64.tar.gz"
      sha256 "3b10688d625fb12bf65794b7b505ab89075870d11f455807395c2ac2e58f0b58"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shloop/google-book-scraper/releases/download/v0.4.0/google-book-scraper-0.4.0-linux-amd64.tar.gz"
      sha256 "ad4ca75ffc65f9623943363c6d9e2416d9c0bb945a66cd450a3685e1dd20dd7d"
    end

    on_arm do
      url "https://github.com/shloop/google-book-scraper/releases/download/v0.4.0/google-book-scraper-0.4.0-linux-arm64.tar.gz"
      sha256 "11b851cbdd4f3a8222fb9b8342f94ed62ea7ec12041de9b73b111aa70fd91d9c"
    end
  end

  def install
    bin.install "gbscraper"
  end
end
